application: tulz-exp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /jquery.js
  static_files: static/jquery-1.8.2.js
  upload: static/jquery-1.8.2.js

- url: /jquery.timer.js
  static_files: static/jquery.timer.js
  upload: static/jquery.timer.js


- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  mime_type: image/x-icon

- url: /.*
  script: index.app

libraries:
- name: jinja2
  version: latest